version: '3.8'

services:
  db:
    image: mysql:8.0 
    container_name: mysql_db_820

    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: webdb
    ports:
      - "8820:3306"
    volumes:
      - mysql_data_820:/var/lib/mysql
    networks:
      - weblab820
    restart: always

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin_820
    environment:
      PMA_HOST: db 
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root
      UPLOAD_LIMIT: 64M
    ports:
      - "8830:80"
    depends_on:
      - db
    networks:
      - weblab820
    restart: always

networks:
  weblab820:
    driver: bridge

volumes:
  mysql_data_820:
    driver: local